# Generated by Django 3.2.24 on 2024-02-29 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(help_text="Enter the author's name", max_length=100),
        ),
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.TextField(default='No description available.', help_text='Enter the description of the item'),
        ),
        migrations.AlterField(
            model_name='book',
            name='publisher',
            field=models.CharField(help_text="Enter the publisher's name", max_length=100),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(help_text='Enter the title of the item', max_length=200),
        ),
        migrations.AlterField(
            model_name='game',
            name='description',
            field=models.TextField(default='No description available.', help_text='Enter the description of the item'),
        ),
        migrations.AlterField(
            model_name='game',
            name='genre',
            field=models.CharField(help_text='Enter the genre of the game', max_length=100),
        ),
        migrations.AlterField(
            model_name='game',
            name='platform',
            field=models.CharField(help_text='Enter the platform of the game(e.g., PC, PS4, etc.)', max_length=100),
        ),
        migrations.AlterField(
            model_name='game',
            name='title',
            field=models.CharField(help_text='Enter the title of the item', max_length=200),
        ),
        migrations.AlterField(
            model_name='video',
            name='description',
            field=models.TextField(default='No description available.', help_text='Enter the description of the item'),
        ),
        migrations.AlterField(
            model_name='video',
            name='director',
            field=models.CharField(help_text="Enter the director's name", max_length=100),
        ),
        migrations.AlterField(
            model_name='video',
            name='title',
            field=models.CharField(help_text='Enter the title of the item', max_length=200),
        ),
    ]
